version: '2'
services:
  openculture-app:
    image: openculture
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://openculture-postgresql:5432/openculture
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  openculture-postgresql:
    extends:
      file: postgresql.yml
      service: openculture-postgresql
